spring:
  application:
    name: MyCrudProject
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1460;databaseName=bon_dsv;sendStringParametersAsUnicode=true;encrypt=false;
    username: sa
    password: Passw0rd
  jpa:
    show-sql: true
    properties:
      hibernate:
        boot:
          allow_jdbc_metadata_access: false
        format_sql: true
        dialect: org.hibernate.dialect.SQLServerDialect

    defer-datasource-initialization: false